version: "3"

env:
  DOCKER_BUILDKIT: "1"

tasks:
  docker-run:
    cmds:
      - docker build -t tmp .
      - docker run --rm -it -p 8080:8080 tmp .

  build-run:
    env:
      IDLE_TIMEOUT: 24h
      PRETTY: 1
      DEBUG: 1
    cmds:
      - |
        (cd frontend && npm run dev)&
        frontendPID=$!
        cd backend && go run .
        kill $frontendPID
  deploy:
    cmds:
      - |
        old_machines=$(fly machine list --app beelection --json | jq -r '.[] | .id')
        if [ -z "${old_machines}" ]; then
          echo "no old machines"
        else
          echo ${old_machines} | xargs -n1 fly machine destroy --app beelection --force 
        fi
      - fly m run . -p 8080:8080/tcp:tls:http  -p 443:8080/tcp:tls:http -p 80:8080/tcp:http --region fra -a beelection
